CREATE TABLE `database_tps`.`01_table_all_transit` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time` TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `line_id` VARCHAR(20) NOT NULL,
    `pg` VARCHAR(20) NOT NULL,
    `line_name` VARCHAR(20) NOT NULL,
    `name_product` VARCHAR(20) NOT NULL,
    `target` VARCHAR(20) NOT NULL,
    `actual` VARCHAR(20) NOT NULL,
    `loading_time` VARCHAR(20) NOT NULL,
    `efficiency` VARCHAR(20) NOT NULL,
    `delay` VARCHAR(20) NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `cycle_time` VARCHAR(20) NOT NULL,
    `time_trouble` VARCHAR(20) NOT NULL,
    `time_trouble_quality` VARCHAR(20) NOT NULL,
    `andon` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;
CREATE TABLE `database_tps`.`02_table_all_transit_hikitori` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time` TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `line_id` VARCHAR(20) NOT NULL,
    `pg` VARCHAR(20) NOT NULL,
    `line_name` VARCHAR(20) NOT NULL,
    `name_product` VARCHAR(20) NOT NULL,
    `target` VARCHAR(20) NOT NULL,
    `actual` VARCHAR(20) NOT NULL,
    `loading_time` VARCHAR(20) NOT NULL,
    `efficiency` VARCHAR(20) NOT NULL,
    `delay` VARCHAR(20) NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `cycle_time` VARCHAR(20) NOT NULL,
    `time_trouble` VARCHAR(20) NOT NULL,
    `time_trouble_quality` VARCHAR(20) NOT NULL,
    `andon` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;
CREATE TABLE `database_tps`.`03_table_all_transit_montiv` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time` TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `line_id` VARCHAR(20) NOT NULL,
    `pg` VARCHAR(20) NOT NULL,
    `line_name` VARCHAR(20) NOT NULL,
    `name_product` VARCHAR(20) NOT NULL,
    `target` VARCHAR(20) NOT NULL,
    `actual` VARCHAR(20) NOT NULL,
    `loading_time` VARCHAR(20) NOT NULL,
    `efficiency` VARCHAR(20) NOT NULL,
    `delay` VARCHAR(20) NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `cycle_time` VARCHAR(20) NOT NULL,
    `time_trouble` VARCHAR(20) NOT NULL,
    `time_trouble_quality` VARCHAR(20) NOT NULL,
    `andon` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;
CREATE TABLE `database_tps`.`01_table_spam` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `time` TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `data1` VARCHAR(20) NOT NULL,
    `data2` VARCHAR(20) NOT NULL,
    `data3` VARCHAR(20) NOT NULL,
    `data4` VARCHAR(20) NOT NULL,
    `data5` VARCHAR(20) NOT NULL,
    `data6` VARCHAR(20) NOT NULL,
    `data7` VARCHAR(20) NOT NULL,
    `data8` VARCHAR(20) NOT NULL,
    `data9` VARCHAR(20) NOT NULL,
    `data10` VARCHAR(20) NOT NULL,
    `data11` VARCHAR(20) NOT NULL,
    `data12` VARCHAR(20) NOT NULL,
    `data13` VARCHAR(20) NOT NULL,
    `data14` VARCHAR(20) NOT NULL,
    `data15` VARCHAR(20) NOT NULL,
    `data16` VARCHAR(20) NOT NULL,
    `data17` VARCHAR(20) NOT NULL,
    `data18` VARCHAR(20) NOT NULL,
    `data19` VARCHAR(20) NOT NULL,
    `data20` VARCHAR(20) NOT NULL,
    `data21` VARCHAR(20) NOT NULL,
    `data22` VARCHAR(20) NOT NULL,
    `data23` VARCHAR(20) NOT NULL,
    `data24` VARCHAR(20) NOT NULL,
    `data25` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;
